# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  libFramework: 'netstandard2.0'
  appFramework: 'net6.0'
  # pay attention to  slashes
  testsProject:  'sources/Test/OpenMcdf.Test/OpenMcdf.Test.csproj'
  extensionTestsProject: 'sources/Test/OpenMcdf.Extensions.Test/OpenMcdf.Extensions.Test.csproj'
  buildProject: 'sources/OpenMcdf/OpenMcdf.csproj'
  # without filter it  will timoeout in azure AFTER 60+ min
  testFilter: 'Name!=Test_FIX_BUG_GH_14&Name!=Test_FIX_BUG_GH_15'

steps:
- script: dotnet build --configuration $(buildConfiguration) -f $(libFramework) $(buildProject)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test -f $(appFramework)  $(testsProject) --filter="$(testFilter)" --logger trx
  displayName: 'OpenMcdf unit tests'

- script: dotnet test $(extensionTestsProject) --logger trx
  displayName: 'OpenMcdf.Extensions unit tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
